name: AntiSeedCracker
version: '${version}'
main: me.gadse.antiseedcracker.AntiSeedCracker
api-version: '1.21'
folia-supported: true
authors: [Gadse]
description: Modifies the hashed seed sent to clients upon joining to make cracking the seed of your world harder
depend: ["ProtocolLib"]

commands:
  antiseedcracker:
    permission: "antiseedcracker.admin"
    usage: /antiseedcracker [reload | slime <reload|check|find|shuffle-salt>]
    description: AntiSeedCracker control command (seed-randomiser, end modifiers, slime anti-crack module)
    aliases:
      - asc

permissions:
  antiseedcracker.admin:
    default: op
